#ifndef crypto_sign_H
#define crypto_sign_H

#include "crypto_sign_sphincs256haraka.h"

#define crypto_sign crypto_sign_sphincs256haraka
#define crypto_sign_open crypto_sign_sphincs256haraka_open
#define crypto_sign_keypair crypto_sign_sphincs256haraka_keypair
#define crypto_sign_BYTES crypto_sign_sphincs256haraka_BYTES
#define crypto_sign_SECRETKEYBYTES crypto_sign_sphincs256haraka_SECRETKEYBYTES
#define crypto_sign_PUBLICKEYBYTES crypto_sign_sphincs256haraka_PUBLICKEYBYTES
#define crypto_sign_DETERMINISTIC crypto_sign_sphincs256haraka_DETERMINISTIC
#define crypto_sign_PRIMITIVE "sphincs256haraka"
#define crypto_sign_IMPLEMENTATION crypto_sign_sphincs256haraka_IMPLEMENTATION
#define crypto_sign_VERSION crypto_sign_sphincs256haraka_VERSION

#endif
